### ISSUE TITLE
请问现在知乎web上的登陆是点击倒立文字,为何这个项目中的zhihu.py里依旧可以通过图片验证码来登陆?

### ISSUE THREAD

**Issue by MQL9011** [xchaoinfo/fuck-login#105]
请问现在知乎web上的登陆是点击倒立文字,为何这个项目中的zhihu.py里依旧可以通过图片验证码来登陆?
这个图片验证码在网页上并没有显示呀,很好奇是从哪里获得的这个图片验证码

**Comment by iamxuwenjin** [comment]
代码里用的是老的验证码接口，现在是点击倒立文字，但老的识别图片字母的方式还能用，你直接请求代码里这个URL看看就明白了

**Comment by MQL9011** [comment]
@iamxuwenjin  谢谢懂了...万一哪天老接口木有了咋办

**Comment by iamxuwenjin** [comment]
用selenium框架调用浏览器手动输入
