### ISSUE TITLE
知乎登陆不进去

### ISSUE THREAD

**Issue by SunCrazy** [xchaoinfo/fuck-login#15]
完全copy您的代码，得到的结果是"验证码会话无效 :(”，接下来，在登陆之后尝试获取只有正常登陆才能获取的页面，但是依然获取的是登陆页面的代码。
`url = 'https://www.zhihu.com/people/shi-wei-56-10/followees'`
 `page = session.get(url, headers=headers)`
 `print page.text`

**Comment by xchaoinfo** [comment]
知乎的验证码获取的方式改了，thanks for your issue, I will solve it later.

**Comment by SunCrazy** [comment]
对的对的，我刚发现。最后应该加一个“&type=login”，我刚测试了一下，成功了

**Comment by xchaoinfo** [comment]
问题，我已经修复了，thanks for your issue again!
