### ISSUE TITLE
知乎isLogin() 报SSLError错误

### ISSUE THREAD

**Issue by Zonzely** [xchaoinfo/fuck-login#18]
知乎isLogin()函数，报错
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

添加`verify=False`后不报错了，有一些警告信息。
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

**Comment by xchaoinfo** [comment]
你最后，可以登录成功吗？
错误原因是不是你的 requests 的问题？ 使用 Python 3 安装最新的 requests 看是否还存在这个问题。

**Comment by Sunkworld** [comment]
是不是用了python2...https://www.zhihu.com/question/40025043/answer/89258748

**Comment by Zonzely** [comment]
用的是python3.4，可以登录成功，就是验证登录的函数isLogin()会报错。
我将requests升级后，问题解决了。谢谢！

**Comment by xchaoinfo** [comment]
知乎的登录，又有了点变化，找个时间，我把程序重写下。

**Comment by SherryDay** [comment]
您好，我试着get这个地址captchaURL = 'http://www.zhihu.com/captcha.gif?r=146...&type=login',r值是当前的时间戳加3个随机值，但还是返回验证码会话错误。您有空能看下么？ 绝不是伸手党，谢谢。

**Comment by xchaoinfo** [comment]
简单总结:
1. 这个问题的出现是由于 Python 的版本低，或者 requests 的版本低。
2. 可以通过升级 requests 的版本，如果还有问题，可以指定 SSL 的版本。最后，如果还是没有解决，那就升级你的 Python 版本吧。
