### ISSUE TITLE
登录雪球网的

### ISSUE THREAD

**Issue by CoderLJW** [xchaoinfo/fuck-login#20]

**Comment by xchaoinfo** [comment]
雪球的模拟登录已经写好了 https://github.com/xchaoinfo/fuck-login/tree/master/012%20xueqiu.com
1、xueqiu.com 全网 https 后，对 headers 的检测比较严格
2、密码采用了 md5  的加密方式

**Comment by Rockyzsu** [comment]
像这种加密的md5或者多重md5的，楼主是怎样发现的？

**Comment by xchaoinfo** [comment]
@Rockyzsu 这个我是通过经验判断后，然后验证的，因为我对于几种加密的方式已经熟悉了，
以前写的时候，都是去阅读 js 源码的。
