### ISSUE TITLE
关于知乎的带cookie访问

### ISSUE THREAD

**Issue by syyunong** [xchaoinfo/fuck-login#21]
知乎的那个可以登录，但是登陆了以后，如何带cookie访问一个url啊...
直接在后面接urllib.request.urlopen(url).read()，这样好像并不能带cookie,不知道应该怎么写呢？

抱歉刚上手，百度的结果试了一下都有些问题，要不就是python2的...求解~~

**Comment by xchaoinfo** [comment]
session.get(url)

**Comment by syyunong** [comment]
thx!解决了
