### ISSUE TITLE
模拟登陆微博  IndexError: list index out of range

### ISSUE THREAD

**Issue by Muzeffer** [xchaoinfo/fuck-login#25]
` uuid_res = re.findall(uuid_pa, uuid, re.S)[0]
`

>  uuid_res = re.findall(uuid_pa, uuid, re.S)[0]
IndexError: list index out of range

**Comment by Muzeffer** [comment]
排查后发现是网络问题，代码没有问题，成功模拟登录

**Comment by seaweiqing** [comment]
我登录的时候也报了这个错啊，真的是网络问题吗？应该怎么解决？

**Comment by seaweiqing** [comment]
@2efPer 请问您之前是怎么解决这个报错的呀，感谢
