### ISSUE TITLE
电信189网上营业厅

### ISSUE THREAD

**Issue by Huayx** [xchaoinfo/fuck-login#29]
http://ah.189.cn/sso/login?returnUrl=%2Fservice%2Faccount%2Finit.action
1.验证码简单易识别
2.post登陆Cookies不易获取
3.请教一下大牛

**Comment by xchaoinfo** [comment]
1. 验证码的识别并不是很难，可以使用 Pillow 这个模块简单处理下，然后用 Pytesseract 驱动 google 开源的 tesseract-ocr 来识别
2. 密码采用了 128 的加密方式，可能是 RSA 加密，这个比较常见，但是具体的加密方式需要阅读 js 源码了。
