### ISSUE TITLE
华中科技大学hub系统模拟登录遇到困难

### ISSUE THREAD

**Issue by ZsnnsZ** [xchaoinfo/fuck-login#42]
华科的教务系统http://hub.hust.edu.cn/index.jsp用了中转登陆，转了几次弯，密码加了两次密，绕糊涂了，大神可以帮忙吗，我可以提供账号密码

**Comment by ZsnnsZ** [comment]
我自己解决了，在此贴上[python爬取华科hub教务系统课表](https://github.com/ZsnnsZ/hubspider)

**Comment by CuteSephiroth** [comment]
在这里都能遇到校友23333
