### ISSUE TITLE
猎聘网猎头自动登录

### ISSUE THREAD

**Issue by xianhu** [xchaoinfo/fuck-login#6]
研究了半天猎头登录的流程，没有发现任何下手的地方。
注意是登录猎头账号，不是求职者账号。
谢谢。

**Comment by xchaoinfo** [comment]
好的，已经收到了你的请求，Todolist 完成后，时间允许的话，会更新这个网站的模拟登录，你也可以看看已经解决的模拟登录，也许可以从中找到某些相似的东西，可以解决你的问题。
thx

**Comment by xianhu** [comment]
OK，你写的这些我看过一些了，很厉害，我也都能自己写代码模拟走通，也很明白怎么登录流程。
谢谢。

**Comment by xchaoinfo** [comment]
[henry51](https://github.com/henry51) 已经解决了这个问题
