### ISSUE TITLE
51Job登录

### ISSUE THREAD

**Issue by rendongsc** [xchaoinfo/fuck-login#60]
楼主，可以试试51Job登录吗？谢谢！

**Comment by 849845960** [comment]
这个我们也要用。

**Comment by xchaoinfo** [comment]
这个网站的登录很简单，密码什么的都没有加密，可以参考知乎的那个登录。
知乎的登录的过程，我已经录制成视频了，可以到知乎专栏查看[可爱的 Python](https://zhuanlan.zhihu.com/xchaoinfo)
