### ISSUE TITLE
按照这个思路写的知乎登录，输入完验证码后，一直报验证码无效。。

### ISSUE THREAD

**Issue by linzhi** [xchaoinfo/fuck-login#71]
RT，不知道啥原因。。，即使输入错误的密码  也是提示这个

**Comment by xchaoinfo** [comment]
- 请确保你参考的是 最新的代码
- 建议手动登录几次知乎，观察验证码的类型，如果是倒着汉字，那就是知乎对于登录频繁的用户做了限制，升级了验证码的类型。

**Comment by linzhi** [comment]
感谢解答，已经解决了，我没有在取了t之后就下载图片，而是打印了url 再手动复制到浏览器去打开。。。这样导致看到的验证码不一样。

就是说即使t参数一样，不同时刻请求得到的验证码也不一样
